export const CardNamesResource: string[] = [
    // https://www.bestnamegenerator.com/legendary-creature-name-generator
    "Vasqai",
    "Jacrou",
    "Draffe",
    "Aklongi",
    "Vananshod",
    "Grintaond",
    "Calclaurn",
    "Hibasqaiff",
    "Dullagiond",
    "Sillsai",
    "Shuane",
    "Acamp",
    "Teacorn",
    "Shaocore",
    "Ocore",
    "Vrupie",
    "Strehorn",
    "Wiemera",
    "Woumera",
    "Skiataur",
    "Deique",
];